import jsPDF from 'jspdf';
import { Parish } from '../types';

export interface TableColumn {
  header: string;
  width: number;
  align?: 'left' | 'right' | 'center';
}

export interface TableRow {
  cells: string[];
  bold?: boolean;
  bg?: string;
  color?: string;
}

export interface TableData {
  columns: TableColumn[];
  rows: TableRow[];
}

export interface ReportSection {
  title?: string;
  table?: TableData;
  text?: string;
}

export interface ReportData {
  title: string;
  parish: Parish;
  generatedBy: string;
  generatedAt: Date;
  periodStart: string;
  periodEnd: string;
  sections: ReportSection[];
  reportType: string;
}

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_HEIGHT = 20;

function formatCurrency(val: number): string {
  return val?.toLocaleString('en-TZ', { minimumFractionDigits: 2 }) || '0.00';
}

class PdfReportBuilder {
  private doc: jsPDF;
  private y: number = MARGIN;
  private page: number = 1;

  constructor() {
    this.doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  }

  private checkPage(needed: number = 15): void {
    if (this.y + needed > PAGE_HEIGHT - FOOTER_HEIGHT - MARGIN) {
      this.addFooter();
      this.doc.addPage();
      this.page++;
      this.y = MARGIN;
    }
  }

  private addFooter(): void {
    const footerY = PAGE_HEIGHT - FOOTER_HEIGHT;
    this.doc.setLineWidth(0.3);
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(MARGIN, footerY, PAGE_WIDTH - MARGIN, footerY);

    this.doc.setFontSize(7);
    this.doc.setFont('helvetica', 'italic');
    this.doc.setTextColor(120, 120, 120);
    const footerText = 'Generated by OCMIS - OurKanisa Church Management Information System';
    const fw = this.doc.getTextWidth(footerText);
    this.doc.text(footerText, (PAGE_WIDTH - fw) / 2, footerY + 7);

    const pageText = `Page ${this.page}`;
    const pw = this.doc.getTextWidth(pageText);
    this.doc.text(pageText, PAGE_WIDTH - MARGIN - pw, footerY + 7);
  }

  async addHeader(parish: Parish): Promise<void> {
    // Logo
    if (parish.logo_url) {
      try {
        const logoData = await loadImageAsDataUrl(parish.logo_url);
        if (logoData) {
          this.doc.addImage(logoData, 'PNG', MARGIN, this.y, 22, 22);
        }
      } catch { /* skip */ }
    }

    // Parish name centered
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(0, 0, 0);
    const name = parish.parish_name.toUpperCase();
    const nw = this.doc.getTextWidth(name);
    this.doc.text(name, (PAGE_WIDTH - nw) / 2, this.y + 6);
    this.y += 9;

    // Address
    if (parish.physical_address) {
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(80, 80, 80);
      const lines = this.doc.splitTextToSize(parish.physical_address, CONTENT_WIDTH);
      for (const line of lines) {
        const lw = this.doc.getTextWidth(line);
        this.doc.text(line, (PAGE_WIDTH - lw) / 2, this.y);
        this.y += 4;
      }
    }

    // Contact
    if (parish.contact_phone || parish.contact_email) {
      this.doc.setFontSize(8);
      let ct = '';
      if (parish.contact_phone) ct += `Tel: ${parish.contact_phone}`;
      if (parish.contact_phone && parish.contact_email) ct += ' | ';
      if (parish.contact_email) ct += parish.contact_email;
      const cw = this.doc.getTextWidth(ct);
      this.doc.text(ct, (PAGE_WIDTH - cw) / 2, this.y);
      this.y += 5;
    }

    // Separator
    this.doc.setLineWidth(0.5);
    this.doc.setDrawColor(79, 70, 229);
    this.doc.line(MARGIN, this.y, PAGE_WIDTH - MARGIN, this.y);
    this.y += 8;
  }

  addTitle(title: string): void {
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(0, 0, 0);
    const tw = this.doc.getTextWidth(title);
    this.doc.text(title.toUpperCase(), (PAGE_WIDTH - tw) / 2, this.y);
    this.y += 7;
  }

  addMetadata(generatedBy: string, generatedAt: Date, periodStart: string, periodEnd: string): void {
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(80, 80, 80);

    this.doc.text(`Period: ${periodStart} to ${periodEnd}`, MARGIN, this.y);
    this.y += 4;
    this.doc.text(`Generated By: ${generatedBy}`, MARGIN, this.y);
    this.y += 4;
    this.doc.text(`Generated At: ${generatedAt.toLocaleString()}`, MARGIN, this.y);
    this.y += 6;

    this.doc.setLineWidth(0.3);
    this.doc.setDrawColor(220, 220, 220);
    this.doc.line(MARGIN, this.y, PAGE_WIDTH - MARGIN, this.y);
    this.y += 6;
  }

  addSectionTitle(title: string): void {
    this.checkPage(12);
    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(30, 30, 30);
    this.doc.text(title, MARGIN, this.y);
    this.y += 6;
  }

  addTable(table: TableData): void {
    const { columns, rows } = table;
    const colWidths = columns.map(c => c.width);
    const totalWidth = colWidths.reduce((a, b) => a + b, 0);
    const startX = MARGIN + (CONTENT_WIDTH - totalWidth) / 2;
    const rowHeight = 7;

    // Header
    this.checkPage(rowHeight * 2);
    this.doc.setFillColor(79, 70, 229);
    this.doc.rect(startX, this.y - 5, totalWidth, rowHeight, 'F');
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(255, 255, 255);

    let x = startX;
    for (let i = 0; i < columns.length; i++) {
      const align = columns[i].align || 'left';
      const text = columns[i].header;
      const tw = this.doc.getTextWidth(text);
      const offset = align === 'right' ? colWidths[i] - tw - 3 : align === 'center' ? (colWidths[i] - tw) / 2 : 3;
      this.doc.text(text, x + offset, this.y - 0.5);
      x += colWidths[i];
    }
    this.y += rowHeight;

    // Rows
    for (let ri = 0; ri < rows.length; ri++) {
      this.checkPage(rowHeight + 5);
      const row = rows[ri];

      // Background
      if (row.bg) {
        const [r, g, b] = row.bg.split(',').map(Number);
        this.doc.setFillColor(r, g, b);
        this.doc.rect(startX, this.y - 5, totalWidth, rowHeight, 'F');
      } else if (ri % 2 === 1) {
        this.doc.setFillColor(248, 250, 252);
        this.doc.rect(startX, this.y - 5, totalWidth, rowHeight, 'F');
      }

      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', row.bold ? 'bold' : 'normal');
      this.doc.setTextColor(row.color ? parseInt(row.color) : 30, 30, 30);

      x = startX;
      for (let i = 0; i < row.cells.length && i < columns.length; i++) {
        const align = columns[i].align || 'left';
        const text = row.cells[i];
        const tw = this.doc.getTextWidth(text);
        const offset = align === 'right' ? colWidths[i] - tw - 3 : align === 'center' ? (colWidths[i] - tw) / 2 : 3;
        this.doc.text(text, x + offset, this.y - 0.5);
        x += colWidths[i];
      }
      this.y += rowHeight;
    }

    // Bottom border
    this.doc.setLineWidth(0.3);
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(startX, this.y - 2, startX + totalWidth, this.y - 2);
    this.y += 4;
  }

  addText(text: string): void {
    this.checkPage(10);
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(30, 30, 30);
    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH);
    for (const line of lines) {
      this.checkPage(6);
      this.doc.text(line, MARGIN, this.y);
      this.y += 5;
    }
  }

  addSummaryRow(label: string, value: string, isBold = false, valueColor?: string): void {
    this.checkPage(10);
    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    this.doc.setTextColor(30, 30, 30);
    this.doc.text(label, MARGIN, this.y);

    if (valueColor) {
      const [r, g, b] = valueColor.split(',').map(Number);
      this.doc.setTextColor(r, g, b);
    }
    const vw = this.doc.getTextWidth(value);
    this.doc.text(value, PAGE_WIDTH - MARGIN - vw, this.y);
    this.doc.setTextColor(30, 30, 30);
    this.y += 7;
  }

  addSeparator(): void {
    this.y += 2;
    this.doc.setLineWidth(0.3);
    this.doc.setDrawColor(220, 220, 220);
    this.doc.line(MARGIN, this.y, PAGE_WIDTH - MARGIN, this.y);
    this.y += 5;
  }

  finalize(): jsPDF {
    this.addFooter();
    return this.doc;
  }

  getY(): number { return this.y; }
  setY(y: number): void { this.y = y; }
}

async function loadImageAsDataUrl(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) return null;
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// --- Public API ---

export async function generateReportPdf(data: ReportData): Promise<jsPDF> {
  const builder = new PdfReportBuilder();
  await builder.addHeader(data.parish);
  builder.addTitle(data.title);
  builder.addMetadata(data.generatedBy, data.generatedAt, data.periodStart, data.periodEnd);

  for (const section of data.sections) {
    if (section.title) builder.addSectionTitle(section.title);
    if (section.table) builder.addTable(section.table);
    if (section.text) builder.addText(section.text);
    builder.addSeparator();
  }

  return builder.finalize();
}

export async function downloadReportPdf(data: ReportData): Promise<void> {
  const doc = await generateReportPdf(data);
  const filename = `${data.title.toLowerCase().replace(/\s+/g, '_')}_${data.generatedAt.getTime()}.pdf`;
  doc.save(filename);
}

export async function printReportPdf(data: ReportData): Promise<void> {
  const doc = await generateReportPdf(data);
  const blob = doc.output('blob');
  const url = URL.createObjectURL(blob);
  const printWindow = window.open(url, '_blank');
  if (printWindow) {
    printWindow.addEventListener('load', () => {
      printWindow.print();
    });
  }
}

export { formatCurrency };
